name: "Build Images"
on:
  release:
    types: [released]

  workflow_dispatch:
    inputs:
      tag:
        description: "The tag of the image"
        required: false
        type: string
      updateLatest:
        description: "Update the tag `latest`"
        required: false
        default: true
        type: boolean

jobs:
  get-tags:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate tags
        id: generate-tags
        env:
          INPUT_TAG: ${{ inputs.tag }}
          REGISTRYS: "docker.io/dreamofice/hoyorandom swr.cn-south-1.myhuaweicloud.com/dreamofice/hoyorandom"
          UPDATE_LATEST: ${{ env.GITHUB_REF_TYPE == 'tag' || inputs.updateLatest }}
        run: |
          update_latest=${UPDATE_LATEST};
          if [ -n "${INPUT_TAG}" ]; then
            tag=${INPUT_TAG};
          else
            sudo apt install jq -y
            tag="v$(cat package.json | jq .version -j)";
          fi
          prefix='';
          tags=''
          for registry in ${REGISTRYS}; do
            tags+="${prefix}${registry}:${tag}";
            prefix=",";
            if ${update_latest}; then
              tags+="${prefix}${registry}:latest";
            fi
          done
          echo "tags=${tags}" >> ${GITHUB_OUTPUT};
      - name: Print logs
        env:
          TAGS: ${{ steps.generate-tags.outputs.tags }}
        run: echo -e "Tags:\n${TAGS}"
    outputs:
      tags: ${{ steps.generate-tags.outputs.tags }}

  build-image:
    needs: get-tags
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Huaweicloud
        uses: docker/login-action@v2
        with:
          registry: swr.cn-south-1.myhuaweicloud.com
          username: ${{ secrets.HUAWEICLOUD_USERNAME }}
          password: ${{ secrets.HUAWEICLOUD_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ needs.get-tags.outputs.tags }}
