name: "Build dev images"
on:
  push:
    branches:
      - dev

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Huaweicloud
        uses: docker/login-action@v2
        with:
          registry: swr.cn-south-1.myhuaweicloud.com
          username: ${{ secrets.HUAWEICLOUD_USERNAME }}
          password: ${{ secrets.HUAWEICLOUD_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: docker.io/dreamofice/hoyorandom:dev,swr.cn-south-1.myhuaweicloud.com/dreamofice/hoyorandom:dev
